### PR TITLE
Change the registry.xml to use plone.base.interfaces.resources.IBundleRegistry

### PR DESCRIPTION
**Pull request by cihanandac**
Related to [Issue 193](https://github.com/collective/collective.z3cform.datagridfield/issues/193)

Changed the registry.xml to use "plone.base.interfaces.resources.IBundleRegistry" instead of "Products.CMFPlone.interfaces.IBundleRegistry"

### CODE REVIEW

**Review by petschki — CHANGES_REQUESTED** [review]
LGTM in general but please add a note in CHANGES.txt as we do not use towncrier here.

**Comment by cihanandac** [comment]
I added a news item as it is suggested in the CHANGES.rst, I hope this is what you suggested also @petschki.

**Comment by petschki** [comment]
oh, sorry your're right ... we do use towncrier actually. perfect 👍🏼

I'll use your PR to do some housekeeping too if you don't mind (JS dependency updates) then I'll merge

**Review by petschki — APPROVED** [review]
Ah I see, you've forked the repo. So lets merge this and do the housekeeping separately.

It would be better to create a PR directly on `collective` so that other users can change things too ... otherwise you would have to grant access to your repo... but that's for the next one 😉

**Comment by cihanandac** [comment]
I see your point, I will keep this in mind for the next time:) 
Thank you for everything.

**Review by petschki — CHANGES_REQUESTED** [review]
Sorry, two more things:

1. would you please change the interface location also in the uninstall profile ... just the same like in default ...
2. we need an upgrade step to version `6` with the new registry interface ... see the `upgrades` folder. basically the same like its done in `5` without the removals.

**Comment by cihanandac** [comment]
Changed the uninstall profile as well and also included version 6 to the upgrades as requested.
@petschki I have added you as the collaborator to the fork incase if you want to make the housekeeping on it that you mentioned.

**Review by petschki — APPROVED** [review]

**Comment by petschki** [comment]
Thanks! you can remove my access from your repo now ...

**Pull request merged**
