### PR TITLE
Fix object access and relateditems widget

### PR DESCRIPTION
**Pull request by tomgross**
https://github.com/plone/Products.CMFPlone/issues/2446

### CODE REVIEW

**Comment by tomgross** [comment]
@jensens Nice catch! One of the critical positions is here also: https://github.com/plone/plone.app.content/pull/157/files

I guess it should be doable to utilize multi dict integration https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/browser/multi_dict_integration.rst and https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/browser/object_multi_dict_integration.rst

This would need a major version here and is probably Plone 5.2 onwards only.

**Comment by tomgross** [comment]
I think there are other places where subforms are used. Plone 5.2 is still z3c.form 3.6 https://github.com/plone/buildout.coredev/blob/3294533732549b805b74817cf48957c9e48ff63e/versions.cfg

**Comment by jensens** [comment]
Yes, I think this targets Plone 5.2+ only and something we have to address.

**Comment by espenmn** [comment]
Can this be merged (I need this :) )

**Pull request merged**
