### PR TITLE
Fix pat-registry definition

### PR DESCRIPTION
**Pull request by cekk**
On a Plone 5 site, i have the following js error in console.

> require.js:166 Uncaught Error: Module name "pat-registry" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:166)
    at Object.localRequire [as require] (require.js:1411)
    at requirejs (require.js:1757)
    at Object.dataGridField2Functions.createNewRow (datagridfield.js:182)
    at Object.dataGridField2Functions.autoInsertRow (datagridfield.js:96)
    at Object.dataGridField2Functions.ensureMinimumRows (datagridfield.js:554)
    at HTMLTableSectionElement.<anonymous> (datagridfield.js:in589)
    at Function.each (jquery.js:384)
    at m.fn.init.each (jquery.js:136)
    at HTMLDocument.dataGridField2Functions.init (datagridfield.js:567)

I simply fixed it, using requirejs sintax.
I don't know if this breaks some possible Plone 4 compatibility.

### CODE REVIEW

**Comment by tkimnguyen** [comment]
I see you added the missing datagridfield.js registry entry that I just ran into! (had to switch resource registry to development mode for that file to get served). Any thoughts on the test failures?

**Comment by cekk** [comment]
It's something related to an import only in Plone 5.0 environment.
Seems that the test script doesn't see Products.ATContenttypes, and i don't know why. Maybe we need to include manually that package in test initialization?

Running the instance (or 5.1 tests), everything works.

@jensens any ideas?

**Comment by tdesvenain** [comment]
Hi, i have tested this branch on a 5.1.2 plone site. it does the job ! Thanks !

**Comment by jensens** [comment]
OK, seems we should merge this, but
- CI is broken (also on master, so different problem) 
- CI should no longer check 4.3 if support is discontinued
- README still states support for Plone 4.3
- setup.py install_requires Products.CMFPlone should be '>=5.0'

**Comment by thet** [comment]
Already merged into master with a different PR since: https://github.com/collective/collective.z3cform.datagridfield/pull/79

**Pull request closed without merging**
