### PR TITLE
Fix types validation

### PR DESCRIPTION
**Pull request by foxtrot-dfm1**

### CODE REVIEW

**Comment by gforcada** [comment]
@foxtrot-dfm1 why do you keep closing and re-opening pull requests to fix the same problem? you can always amend a commit or edit them afterwards, `git` is a great and powerful tool ⚒️ 😄

**Comment by foxtrot-dfm1** [comment]
> @foxtrot-dfm1 why do you keep closing and re-opening pull requests to fix the same problem? you can always amend a commit or edit them afterwards, `git` is a great and powerful tool ⚒️ 😄

Sorry i just thought that my solution was wrong :)

**Comment by foxtrot-dfm1** [comment]
@gforcada Hi, ho can I add some tests to this branch? Are there used the autotests?

**Comment by foxtrot-dfm1** [comment]
The problem is that when we try to deserialize for examle the integer field of DictRow, a normal deserializer bypasses the conversion of type at this line https://github.com/plone/plone.restapi/blob/2b0d7421864cb95a9471c96b629a826a42e96f46/src/plone/restapi/deserializer/dxfields.py#L45 so as we have an dictionary at that point. Because of that problem, the our validation can’t comare the String and Integer types. So I decided to make this addional converison for the validation.

**Comment by petschki** [comment]
If it comes to deserialization checkout my PR here https://github.com/collective/collective.z3cform.datagridfield/pull/147 ... this deserializes all columns regarding to theirs schema field deserializers in plone.restapi. Maybe you want to give this a try an provide some feedback there.

**Comment by foxtrot-dfm1** [comment]
> If it comes to deserialization checkout my PR here #147 ... this deserializes all columns regarding to their schema field deserializers in plone.restapi. Maybe you want to give this a try an provide some feedback there.

The your branch solved my problem so will close this pr

**Pull request closed without merging**
