### PR TITLE
Versions for Plone

### PR DESCRIPTION
**Pull request by gbastien**
Hi @jensens,

this will avoid time lost to other people using this ;-)

Thank you, feel free to adapt changes if necessary.

Gauthier

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @jensens @idgserpro 

can this be merged so it is clear what version to use depending on Plone4 or Plone5?

Thank you,

Gauthier

**Comment by jensens** [comment]
thanks!

**Comment by idgserpro** [comment]
This PR seems incomplete... where exactly did you get this information?

> Versions >= 1.3 are for Plone 5+, if you use Plone 4.3, use versions 1.2.x

Right now, in https://github.com/collective/collective.z3cform.datagridfield/blob/7b9e9bf5b449f7994606202a8d6c5e930845082a/setup.py#L21, it says 4.3 is compatible. So this would need to be changed as well.

**Comment by gbastien** [comment]
@idgserpro this PR was merged, indeed setup.py needs to be updated too.

I will do it directly on master if it is ok for you @jensens ?

Gauthier

**Comment by idgserpro** [comment]
@gbastien It might also be interesting to put one:

```Products.CMFPlone >=5.0```

in install_requires.

**Pull request merged**
