### PR TITLE
Plone 6: latest z3c.form and ES6 resources

### PR DESCRIPTION
**Pull request by petschki**
NOTE: Plone 6 only!

~~This is a successor of #116 which reuses the backported `ObjectSubForm`, `ISubformFactory` and `SubformAdapter` in latest `plone.z3cform` master branch and it removes the redundant `AutoExtensibleSubFormAdapter` code completely.~~

~~After implementing a `DataRowConverter` I'm able to access `@@demo-collective.z3cform.datagrid` and see an empty form, but sending the data needs more investigation.~~

EDIT: This got completely rid of the outdated `SubformAdapter` !

### CODE REVIEW

**Comment by Arkusm** [comment]
I tried it in Plone 6.0.0a4, but it doesn't really seem to work. The button to add rows is not displayed correctly and there is a javascript error:
datagridfield

**Comment by Arkusm** [comment]
Also, it doesn't seem to work anymore when you use context source binder and the source argument to the Choice constructor. (This example worked in the previous version):

```
class ITableRowSchema(interface.Interface):
    name = schema.Choice(
        title="One",
        source=VocabularyBinder("some_vocabulary"),
        required=False
    )
    description = schema.TextLine(
        title="Two",
        required=False
    )
```

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 138, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module z3c.form.form, line 136, in updateWidgets
  Module z3c.form.field, line 274, in update
  Module z3c.form.browser.multi, line 63, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 511, in update
  Module collective.z3cform.datagridfield.datagridfield, line 169, in updateWidgets
  Module collective.z3cform.datagridfield.datagridfield, line 140, in getWidget
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.object, line 297, in update
  Module collective.z3cform.datagridfield.datagridfield, line 295, in updateWidgets
  Module z3c.form.object, line 222, in updateWidgets
  Module z3c.form.object, line 216, in setupWidgets
  Module z3c.form.field, line 274, in update
  Module z3c.form.browser.select, line 51, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 233, in update
  Module z3c.form.widget, line 225, in updateTerms
  Module zope.component._api, line 102, in getMultiAdapter
  Module zope.component._api, line 116, in queryMultiAdapter
  Module zope.interface.registry, line 364, in queryMultiAdapter
  Module zope.interface.adapter, line 844, in queryMultiAdapter
  Module z3c.form.term, line 108, in ChoiceTerms
  Module zope.schema._field, line 475, in bind
  Module zope.schema._field, line 465, in _resolve_vocabulary
zope.schema._field.InvalidVocabularyError: Invalid vocabulary <...VocabularyBinder object at 0x7fc1cbe26b80>
```

**Comment by petschki** [comment]
@Arkusm thanks for trying this! Since Plone 6.0.0a4 the static resources must be rewritten to ES6 modules because requirejs is gone. I'll start a draft today here.

The `VocabularyBinder` problem doesn't look like it belongs to datagridfield. What's that `<VocabularyBinder object ... />` ?

Maybe you can try something like this

https://github.com/plone/plone.app.dexterity/blob/692d932f796801325679383aeb384bf4e15ac106/plone/app/dexterity/behaviors/metadata.py#L112-L119

**Comment by Arkusm** [comment]
@petschki  you are right. I ran across a similar problem elsewhere with my own javascript and had to use webpack to create a working bundle.

The VocabularyBinder looks like this and works in all other contexts in Plone 6.0.0a4 and 6.0.0a3 as well.:

```
class VocabularyBinder(object):

    """ A vocabulary binder for simple vocabularies
    """
    zope.interface.implements(IContextSourceBinder)

    def __init__(self, vocabulary_name):
        self.vocabulary_name = vocabulary_name
        super(VocabularyBinder, self).__init__()

    def __call__(self, context):
        items = getattr(portal_vocabularies, self.vocabulary_name)
        terms = [SimpleTerm(value=pair[0],
                            token=pair[0],
                            title=_(pair[1])) for pair in items]
        return SimpleVocabulary(terms)
```
I subsequently took the approach you describe. It works but unfortunately is not very dynamic.

```
@implementer(IVocabularyFactory)
class SomeVocabulary(object):
    """Vocabulary factory
    """
    def __call__(self, context):
        items = getattr(portal_vocabularies,
                        "some_vocabulary")
        terms = [
            SimpleTerm(value=pair[0], token=pair[0], title=_(pair[1])) for pair in items
        ]
        return SimpleVocabulary(terms)

SomeVocabularyFactory = SomeVocabulary()
```

**Comment by petschki** [comment]
alternatively use `plone.autoform.directives` to pass in parameters: 

https://github.com/plone/plone.app.vocabularies/blob/master/plone/app/vocabularies/catalog.py#L727-L735

**Comment by Arkusm** [comment]
Some commits end up like this:

```
2022-05-11 12:44:39,869 ERROR   [plone.app.viewletmanager:114][waitress-3] Error while rendering viewlet-manager=plone.scripts, viewlet=plone.resourceregistries.scripts
Traceback (most recent call last):
  File "/sandboxes/plone-6.0.0a4/eggs/plone.app.viewletmanager-3.1.2-py3.9.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/sandboxes/plone-6.0.0a4/eggs/plone.app.layout-4.0.0a11-py3.9.egg/plone/app/layout/viewlets/common.py", line 79, in render
    return self.index()
  File "/sandboxes/plone-6.0.0a4/eggs/Products.CMFPlone-6.0.0a4-py3.9.egg/Products/CMFPlone/resources/browser/resource.py", line 277, in index
    rendered = self.renderer["js"].render()
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 630, in render
    return u'\n'.join([
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 631, in <listcomp>
    res.render(self.base_url) for res in self.resolver.resolve()
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 318, in render
    'src': self.resource_url(base_url),
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 193, in resource_url
    parts.append(self.unique_key)
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 178, in unique_key
    str(uuid.uuid5(namespace_uuid, self.file_hash))
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 165, in file_hash
    hash_ = base64.b64encode(hash_func(self.file_data).digest())
  File "/sandboxes/plone-6.0.0a4/eggs/Products.CMFPlone-6.0.0a4-py3.9.egg/Products/CMFPlone/resources/webresource.py", line 22, in file_data
    data = get_resource(self.context, self.resource)
  File "/sandboxes/plone-6.0.0a4/eggs/Products.CMFPlone-6.0.0a4-py3.9.egg/Products/CMFPlone/resources/utils.py", line 54, in get_resource
    resource = context.unrestrictedTraverse(path)
  File "/sandboxes/plone-6.0.0a4/eggs/Zope-5.5.1-py3.9.egg/OFS/Traversable.py", line 347, in unrestrictedTraverse
    raise e
  File "/sandboxes/plone-6.0.0a4/eggs/Zope-5.5.1-py3.9.egg/OFS/Traversable.py", line 301, in unrestrictedTraverse
    next = obj[name]
  File "/sandboxes/plone-6.0.0a4/eggs/zope.browserresource-4.4-py3.9.egg/zope/browserresource/directory.py", line 91, in __getitem__
    raise KeyError(name)
KeyError: 'datagridfield-bundle-compiled.js'
2022-05-11 12:44:39,957 ERROR   [plone.app.viewletmanager:114][waitress-3] Error while rendering viewlet-manager=plone.htmlhead.links, viewlet=plone.resourceregistries.styles
Traceback (most recent call last):
  File "/sandboxes/plone-6.0.0a4/eggs/plone.app.viewletmanager-3.1.2-py3.9.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/sandboxes/plone-6.0.0a4/eggs/plone.app.layout-4.0.0a11-py3.9.egg/plone/app/layout/viewlets/common.py", line 79, in render
    return self.index()
  File "/sandboxes/plone-6.0.0a4/eggs/Products.CMFPlone-6.0.0a4-py3.9.egg/Products/CMFPlone/resources/browser/resource.py", line 288, in index
    rendered = self.renderer["css"].render()
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 630, in render
    return u'\n'.join([
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 631, in <listcomp>
    res.render(self.base_url) for res in self.resolver.resolve()
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 391, in render
    'href': self.resource_url(base_url),
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 193, in resource_url
    parts.append(self.unique_key)
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 178, in unique_key
    str(uuid.uuid5(namespace_uuid, self.file_hash))
  File "/sandboxes/plone-6.0.0a4/eggs/webresource-1.0-py3.9-linux-x86_64.egg/webresource/_api.py", line 165, in file_hash
    hash_ = base64.b64encode(hash_func(self.file_data).digest())
  File "/sandboxes/plone-6.0.0a4/eggs/Products.CMFPlone-6.0.0a4-py3.9.egg/Products/CMFPlone/resources/webresource.py", line 22, in file_data
    data = get_resource(self.context, self.resource)
  File "/sandboxes/plone-6.0.0a4/eggs/Products.CMFPlone-6.0.0a4-py3.9.egg/Products/CMFPlone/resources/utils.py", line 54, in get_resource
    resource = context.unrestrictedTraverse(path)
  File "/sandboxes/plone-6.0.0a4/eggs/Zope-5.5.1-py3.9.egg/OFS/Traversable.py", line 347, in unrestrictedTraverse
    raise e
  File "/sandboxes/plone-6.0.0a4/eggs/Zope-5.5.1-py3.9.egg/OFS/Traversable.py", line 301, in unrestrictedTraverse
    next = obj[name]
  File "/sandboxes/plone-6.0.0a4/eggs/zope.browserresource-4.4-py3.9.egg/zope/browserresource/directory.py", line 91, in __getitem__
    raise KeyError(name)
KeyError: 'datagridfield-bundle-compiled.css'
```

The last variant generates the following error:

datagridfield-js-error

**Comment by petschki** [comment]
did you run the upgrade steps ? your registry still has the old JS and CSS resources ... and css isn't needed anymore

**Comment by petschki** [comment]
uh ... sorry, there was a copy&paste error in the bundle name ... datagridfield killed bootstrap bundle. this is fixed now, but you have to reimport the default bundles again... or enter the values manually. these are the boostrap-js defaults

Bildschirmfoto 2022-05-11 um 13 15 17

**Comment by Arkusm** [comment]
What exactly do I need to do to reimport the default bundles? I even tried a completely new buildout with a new database. But the result looks like this

grafik

**Comment by petschki** [comment]
you can go to `portal_setup -> Import` select `plone.staticresources:default` from the "Profile by id" selector and import all steps ... this should set the resource registry to default

**Comment by petschki** [comment]
but your error is because the `datagrid-bundle` has a missing `depends=plone` and therefore gets called before jquery bundle ... I've fixed that ...

**Comment by Arkusm** [comment]
Looks different, only one column is still displayed but it does not work...

grafik

**Comment by Arkusm** [comment]
Is this working for you now? I still get this source map error, can't press the button for the next field

grafik

and also can't save:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module eteaching.policy2.browser.edit, line 20, in __call__
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.add, line 138, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 301, in __call__
  Module z3c.form.button, line 159, in __call__
  Module plone.dexterity.browser.add, line 112, in handleAdd
  Module z3c.form.group, line 100, in extractData
  Module z3c.form.group, line 67, in extractData
  Module z3c.form.form, line 148, in extractData
  Module z3c.form.field, line 331, in extract
  Module z3c.form.field, line 297, in _extract
  Module collective.z3cform.datagridfield.datagridfield, line 356, in validate
  Module collective.z3cform.datagridfield.datagridfield, line 356, in <listcomp>
AttributeError: 'DataGridFieldObject' object has no attribute 'subform'
```

**Comment by petschki** [comment]
not there yet ... there are issues as you described due to the removed subform implementation. still fighting with z3c.form here ...

**Comment by mauritsvanrees** [comment]
I get the same AttributeError. I got the same error two weeks or so ago.

The UI looks _much_ nicer now though. Thanks!

**Comment by petschki** [comment]
@Arkusm I've been able to fix the issues. Are you able to test the latest changes again?

**Review by mauritsvanrees — APPROVED** [review]
I tried it in a Plone 6 project and it worked. Even with a portal_type that uses three datagridfields. A few minor glitches, but nothing serious, we can look at that later. For me, this can be merged.

**Comment by Arkusm** [comment]
I have tested it. It works very well and looks great. Thanks for fixing it!

**Pull request merged**
